// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VehicleStatusInfo.proto

package com.iammybest.hbase.springboot.hbase.protobuf;

/**
 * Protobuf type {@code com.timanetworks.tpc.entity.hbase.protobuf.VehicleStatusItems}
 */
public  final class VehicleStatusItems extends
    com.google.protobuf.GeneratedMessage
    implements VehicleStatusItemsOrBuilder {
  // Use VehicleStatusItems.newBuilder() to construct.
  private VehicleStatusItems(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private VehicleStatusItems(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final VehicleStatusItems defaultInstance;
  public static VehicleStatusItems getDefaultInstance() {
    return defaultInstance;
  }

  public VehicleStatusItems getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private VehicleStatusItems(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              items_ = new java.util.ArrayList<com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(input.readMessage(com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusInfo.internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusInfo.internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.class, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.Builder.class);
  }

  public static com.google.protobuf.Parser<VehicleStatusItems> PARSER =
      new com.google.protobuf.AbstractParser<VehicleStatusItems>() {
    public VehicleStatusItems parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VehicleStatusItems(input, extensionRegistry);
    }
  };

  @Override
  public com.google.protobuf.Parser<VehicleStatusItems> getParserForType() {
    return PARSER;
  }

  public interface VehicleStatusItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string gvid = 1;
    /**
     * <code>required string gvid = 1;</code>
     */
    boolean hasGvid();
    /**
     * <code>required string gvid = 1;</code>
     */
    String getGvid();
    /**
     * <code>required string gvid = 1;</code>
     */
    com.google.protobuf.ByteString
        getGvidBytes();

    // required string oringinalValue = 2;
    /**
     * <code>required string oringinalValue = 2;</code>
     */
    boolean hasOringinalValue();
    /**
     * <code>required string oringinalValue = 2;</code>
     */
    String getOringinalValue();
    /**
     * <code>required string oringinalValue = 2;</code>
     */
    com.google.protobuf.ByteString
        getOringinalValueBytes();

    // required string value = 3;
    /**
     * <code>required string value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 3;</code>
     */
    String getValue();
    /**
     * <code>required string value = 3;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    // required string signNameZh = 4;
    /**
     * <code>required string signNameZh = 4;</code>
     */
    boolean hasSignNameZh();
    /**
     * <code>required string signNameZh = 4;</code>
     */
    String getSignNameZh();
    /**
     * <code>required string signNameZh = 4;</code>
     */
    com.google.protobuf.ByteString
        getSignNameZhBytes();

    // required string signNameEn = 5;
    /**
     * <code>required string signNameEn = 5;</code>
     */
    boolean hasSignNameEn();
    /**
     * <code>required string signNameEn = 5;</code>
     */
    String getSignNameEn();
    /**
     * <code>required string signNameEn = 5;</code>
     */
    com.google.protobuf.ByteString
        getSignNameEnBytes();

    // required string displayNameZh = 6;
    /**
     * <code>required string displayNameZh = 6;</code>
     */
    boolean hasDisplayNameZh();
    /**
     * <code>required string displayNameZh = 6;</code>
     */
    String getDisplayNameZh();
    /**
     * <code>required string displayNameZh = 6;</code>
     */
    com.google.protobuf.ByteString
        getDisplayNameZhBytes();

    // required string displayNameEn = 7;
    /**
     * <code>required string displayNameEn = 7;</code>
     */
    boolean hasDisplayNameEn();
    /**
     * <code>required string displayNameEn = 7;</code>
     */
    String getDisplayNameEn();
    /**
     * <code>required string displayNameEn = 7;</code>
     */
    com.google.protobuf.ByteString
        getDisplayNameEnBytes();

    // required string valueType = 8;
    /**
     * <code>required string valueType = 8;</code>
     */
    boolean hasValueType();
    /**
     * <code>required string valueType = 8;</code>
     */
    String getValueType();
    /**
     * <code>required string valueType = 8;</code>
     */
    com.google.protobuf.ByteString
        getValueTypeBytes();

    // required string uint = 9;
    /**
     * <code>required string uint = 9;</code>
     */
    boolean hasUint();
    /**
     * <code>required string uint = 9;</code>
     */
    String getUint();
    /**
     * <code>required string uint = 9;</code>
     */
    com.google.protobuf.ByteString
        getUintBytes();

    // required string cateType = 10;
    /**
     * <code>required string cateType = 10;</code>
     */
    boolean hasCateType();
    /**
     * <code>required string cateType = 10;</code>
     */
    String getCateType();
    /**
     * <code>required string cateType = 10;</code>
     */
    com.google.protobuf.ByteString
        getCateTypeBytes();

    // required string signalCode = 11;
    /**
     * <code>required string signalCode = 11;</code>
     */
    boolean hasSignalCode();
    /**
     * <code>required string signalCode = 11;</code>
     */
    String getSignalCode();
    /**
     * <code>required string signalCode = 11;</code>
     */
    com.google.protobuf.ByteString
        getSignalCodeBytes();
  }
  /**
   * Protobuf type {@code com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem}
   */
  public static final class VehicleStatusItem extends
      com.google.protobuf.GeneratedMessage
      implements VehicleStatusItemOrBuilder {
    // Use VehicleStatusItem.newBuilder() to construct.
    private VehicleStatusItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VehicleStatusItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VehicleStatusItem defaultInstance;
    public static VehicleStatusItem getDefaultInstance() {
      return defaultInstance;
    }

    public VehicleStatusItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VehicleStatusItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              gvid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              oringinalValue_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              value_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              signNameZh_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              signNameEn_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              displayNameZh_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              displayNameEn_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              valueType_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              uint_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              cateType_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              signalCode_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusInfo.internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_VehicleStatusItem_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusInfo.internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_VehicleStatusItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
                  com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.class, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder.class);
    }

    public static com.google.protobuf.Parser<VehicleStatusItem> PARSER =
        new com.google.protobuf.AbstractParser<VehicleStatusItem>() {
      public VehicleStatusItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VehicleStatusItem(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<VehicleStatusItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string gvid = 1;
    public static final int GVID_FIELD_NUMBER = 1;
    private Object gvid_;
    /**
     * <code>required string gvid = 1;</code>
     */
    public boolean hasGvid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string gvid = 1;</code>
     */
    public String getGvid() {
      Object ref = gvid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gvid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string gvid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGvidBytes() {
      Object ref = gvid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gvid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string oringinalValue = 2;
    public static final int ORINGINALVALUE_FIELD_NUMBER = 2;
    private Object oringinalValue_;
    /**
     * <code>required string oringinalValue = 2;</code>
     */
    public boolean hasOringinalValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string oringinalValue = 2;</code>
     */
    public String getOringinalValue() {
      Object ref = oringinalValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          oringinalValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string oringinalValue = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOringinalValueBytes() {
      Object ref = oringinalValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        oringinalValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private Object value_;
    /**
     * <code>required string value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string value = 3;</code>
     */
    public String getValue() {
      Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string signNameZh = 4;
    public static final int SIGNNAMEZH_FIELD_NUMBER = 4;
    private Object signNameZh_;
    /**
     * <code>required string signNameZh = 4;</code>
     */
    public boolean hasSignNameZh() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string signNameZh = 4;</code>
     */
    public String getSignNameZh() {
      Object ref = signNameZh_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signNameZh_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string signNameZh = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSignNameZhBytes() {
      Object ref = signNameZh_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signNameZh_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string signNameEn = 5;
    public static final int SIGNNAMEEN_FIELD_NUMBER = 5;
    private Object signNameEn_;
    /**
     * <code>required string signNameEn = 5;</code>
     */
    public boolean hasSignNameEn() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string signNameEn = 5;</code>
     */
    public String getSignNameEn() {
      Object ref = signNameEn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signNameEn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string signNameEn = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSignNameEnBytes() {
      Object ref = signNameEn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signNameEn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string displayNameZh = 6;
    public static final int DISPLAYNAMEZH_FIELD_NUMBER = 6;
    private Object displayNameZh_;
    /**
     * <code>required string displayNameZh = 6;</code>
     */
    public boolean hasDisplayNameZh() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string displayNameZh = 6;</code>
     */
    public String getDisplayNameZh() {
      Object ref = displayNameZh_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          displayNameZh_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string displayNameZh = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayNameZhBytes() {
      Object ref = displayNameZh_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        displayNameZh_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string displayNameEn = 7;
    public static final int DISPLAYNAMEEN_FIELD_NUMBER = 7;
    private Object displayNameEn_;
    /**
     * <code>required string displayNameEn = 7;</code>
     */
    public boolean hasDisplayNameEn() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string displayNameEn = 7;</code>
     */
    public String getDisplayNameEn() {
      Object ref = displayNameEn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          displayNameEn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string displayNameEn = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayNameEnBytes() {
      Object ref = displayNameEn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        displayNameEn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string valueType = 8;
    public static final int VALUETYPE_FIELD_NUMBER = 8;
    private Object valueType_;
    /**
     * <code>required string valueType = 8;</code>
     */
    public boolean hasValueType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string valueType = 8;</code>
     */
    public String getValueType() {
      Object ref = valueType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          valueType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string valueType = 8;</code>
     */
    public com.google.protobuf.ByteString
        getValueTypeBytes() {
      Object ref = valueType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        valueType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string uint = 9;
    public static final int UINT_FIELD_NUMBER = 9;
    private Object uint_;
    /**
     * <code>required string uint = 9;</code>
     */
    public boolean hasUint() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string uint = 9;</code>
     */
    public String getUint() {
      Object ref = uint_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uint_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uint = 9;</code>
     */
    public com.google.protobuf.ByteString
        getUintBytes() {
      Object ref = uint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string cateType = 10;
    public static final int CATETYPE_FIELD_NUMBER = 10;
    private Object cateType_;
    /**
     * <code>required string cateType = 10;</code>
     */
    public boolean hasCateType() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required string cateType = 10;</code>
     */
    public String getCateType() {
      Object ref = cateType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cateType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cateType = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCateTypeBytes() {
      Object ref = cateType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cateType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string signalCode = 11;
    public static final int SIGNALCODE_FIELD_NUMBER = 11;
    private Object signalCode_;
    /**
     * <code>required string signalCode = 11;</code>
     */
    public boolean hasSignalCode() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string signalCode = 11;</code>
     */
    public String getSignalCode() {
      Object ref = signalCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signalCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string signalCode = 11;</code>
     */
    public com.google.protobuf.ByteString
        getSignalCodeBytes() {
      Object ref = signalCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signalCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      gvid_ = "";
      oringinalValue_ = "";
      value_ = "";
      signNameZh_ = "";
      signNameEn_ = "";
      displayNameZh_ = "";
      displayNameEn_ = "";
      valueType_ = "";
      uint_ = "";
      cateType_ = "";
      signalCode_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGvid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOringinalValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignNameZh()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignNameEn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDisplayNameZh()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDisplayNameEn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValueType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUint()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCateType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignalCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGvidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOringinalValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getValueBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSignNameZhBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSignNameEnBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getDisplayNameZhBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getDisplayNameEnBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getValueTypeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getUintBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getCateTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getSignalCodeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGvidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOringinalValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getValueBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSignNameZhBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSignNameEnBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDisplayNameZhBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getDisplayNameEnBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getValueTypeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getUintBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getCateTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getSignalCodeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusInfo.internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_VehicleStatusItem_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusInfo.internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_VehicleStatusItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.class, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder.class);
      }

      // Construct using com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gvid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        oringinalValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        signNameZh_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        signNameEn_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        displayNameZh_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        displayNameEn_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        valueType_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        uint_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        cateType_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        signalCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusInfo.internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_VehicleStatusItem_descriptor;
      }

      public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem getDefaultInstanceForType() {
        return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.getDefaultInstance();
      }

      public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem build() {
        com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem buildPartial() {
        com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem result = new com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gvid_ = gvid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.oringinalValue_ = oringinalValue_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.signNameZh_ = signNameZh_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.signNameEn_ = signNameEn_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.displayNameZh_ = displayNameZh_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.displayNameEn_ = displayNameEn_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.valueType_ = valueType_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.uint_ = uint_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.cateType_ = cateType_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.signalCode_ = signalCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem) {
          return mergeFrom((com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem other) {
        if (other == com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.getDefaultInstance()) return this;
        if (other.hasGvid()) {
          bitField0_ |= 0x00000001;
          gvid_ = other.gvid_;
          onChanged();
        }
        if (other.hasOringinalValue()) {
          bitField0_ |= 0x00000002;
          oringinalValue_ = other.oringinalValue_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000004;
          value_ = other.value_;
          onChanged();
        }
        if (other.hasSignNameZh()) {
          bitField0_ |= 0x00000008;
          signNameZh_ = other.signNameZh_;
          onChanged();
        }
        if (other.hasSignNameEn()) {
          bitField0_ |= 0x00000010;
          signNameEn_ = other.signNameEn_;
          onChanged();
        }
        if (other.hasDisplayNameZh()) {
          bitField0_ |= 0x00000020;
          displayNameZh_ = other.displayNameZh_;
          onChanged();
        }
        if (other.hasDisplayNameEn()) {
          bitField0_ |= 0x00000040;
          displayNameEn_ = other.displayNameEn_;
          onChanged();
        }
        if (other.hasValueType()) {
          bitField0_ |= 0x00000080;
          valueType_ = other.valueType_;
          onChanged();
        }
        if (other.hasUint()) {
          bitField0_ |= 0x00000100;
          uint_ = other.uint_;
          onChanged();
        }
        if (other.hasCateType()) {
          bitField0_ |= 0x00000200;
          cateType_ = other.cateType_;
          onChanged();
        }
        if (other.hasSignalCode()) {
          bitField0_ |= 0x00000400;
          signalCode_ = other.signalCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGvid()) {

          return false;
        }
        if (!hasOringinalValue()) {

          return false;
        }
        if (!hasValue()) {

          return false;
        }
        if (!hasSignNameZh()) {

          return false;
        }
        if (!hasSignNameEn()) {

          return false;
        }
        if (!hasDisplayNameZh()) {

          return false;
        }
        if (!hasDisplayNameEn()) {

          return false;
        }
        if (!hasValueType()) {

          return false;
        }
        if (!hasUint()) {

          return false;
        }
        if (!hasCateType()) {

          return false;
        }
        if (!hasSignalCode()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string gvid = 1;
      private Object gvid_ = "";
      /**
       * <code>required string gvid = 1;</code>
       */
      public boolean hasGvid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string gvid = 1;</code>
       */
      public String getGvid() {
        Object ref = gvid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          gvid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string gvid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGvidBytes() {
        Object ref = gvid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gvid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string gvid = 1;</code>
       */
      public Builder setGvid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        gvid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string gvid = 1;</code>
       */
      public Builder clearGvid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gvid_ = getDefaultInstance().getGvid();
        onChanged();
        return this;
      }
      /**
       * <code>required string gvid = 1;</code>
       */
      public Builder setGvidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        gvid_ = value;
        onChanged();
        return this;
      }

      // required string oringinalValue = 2;
      private Object oringinalValue_ = "";
      /**
       * <code>required string oringinalValue = 2;</code>
       */
      public boolean hasOringinalValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string oringinalValue = 2;</code>
       */
      public String getOringinalValue() {
        Object ref = oringinalValue_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          oringinalValue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string oringinalValue = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOringinalValueBytes() {
        Object ref = oringinalValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          oringinalValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string oringinalValue = 2;</code>
       */
      public Builder setOringinalValue(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        oringinalValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string oringinalValue = 2;</code>
       */
      public Builder clearOringinalValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        oringinalValue_ = getDefaultInstance().getOringinalValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string oringinalValue = 2;</code>
       */
      public Builder setOringinalValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        oringinalValue_ = value;
        onChanged();
        return this;
      }

      // required string value = 3;
      private Object value_ = "";
      /**
       * <code>required string value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string value = 3;</code>
       */
      public String getValue() {
        Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string value = 3;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 3;</code>
       */
      public Builder setValue(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 3;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }

      // required string signNameZh = 4;
      private Object signNameZh_ = "";
      /**
       * <code>required string signNameZh = 4;</code>
       */
      public boolean hasSignNameZh() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string signNameZh = 4;</code>
       */
      public String getSignNameZh() {
        Object ref = signNameZh_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          signNameZh_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string signNameZh = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSignNameZhBytes() {
        Object ref = signNameZh_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          signNameZh_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string signNameZh = 4;</code>
       */
      public Builder setSignNameZh(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        signNameZh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string signNameZh = 4;</code>
       */
      public Builder clearSignNameZh() {
        bitField0_ = (bitField0_ & ~0x00000008);
        signNameZh_ = getDefaultInstance().getSignNameZh();
        onChanged();
        return this;
      }
      /**
       * <code>required string signNameZh = 4;</code>
       */
      public Builder setSignNameZhBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        signNameZh_ = value;
        onChanged();
        return this;
      }

      // required string signNameEn = 5;
      private Object signNameEn_ = "";
      /**
       * <code>required string signNameEn = 5;</code>
       */
      public boolean hasSignNameEn() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string signNameEn = 5;</code>
       */
      public String getSignNameEn() {
        Object ref = signNameEn_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          signNameEn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string signNameEn = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSignNameEnBytes() {
        Object ref = signNameEn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          signNameEn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string signNameEn = 5;</code>
       */
      public Builder setSignNameEn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        signNameEn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string signNameEn = 5;</code>
       */
      public Builder clearSignNameEn() {
        bitField0_ = (bitField0_ & ~0x00000010);
        signNameEn_ = getDefaultInstance().getSignNameEn();
        onChanged();
        return this;
      }
      /**
       * <code>required string signNameEn = 5;</code>
       */
      public Builder setSignNameEnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        signNameEn_ = value;
        onChanged();
        return this;
      }

      // required string displayNameZh = 6;
      private Object displayNameZh_ = "";
      /**
       * <code>required string displayNameZh = 6;</code>
       */
      public boolean hasDisplayNameZh() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string displayNameZh = 6;</code>
       */
      public String getDisplayNameZh() {
        Object ref = displayNameZh_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          displayNameZh_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string displayNameZh = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDisplayNameZhBytes() {
        Object ref = displayNameZh_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          displayNameZh_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string displayNameZh = 6;</code>
       */
      public Builder setDisplayNameZh(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        displayNameZh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string displayNameZh = 6;</code>
       */
      public Builder clearDisplayNameZh() {
        bitField0_ = (bitField0_ & ~0x00000020);
        displayNameZh_ = getDefaultInstance().getDisplayNameZh();
        onChanged();
        return this;
      }
      /**
       * <code>required string displayNameZh = 6;</code>
       */
      public Builder setDisplayNameZhBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        displayNameZh_ = value;
        onChanged();
        return this;
      }

      // required string displayNameEn = 7;
      private Object displayNameEn_ = "";
      /**
       * <code>required string displayNameEn = 7;</code>
       */
      public boolean hasDisplayNameEn() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string displayNameEn = 7;</code>
       */
      public String getDisplayNameEn() {
        Object ref = displayNameEn_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          displayNameEn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string displayNameEn = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDisplayNameEnBytes() {
        Object ref = displayNameEn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          displayNameEn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string displayNameEn = 7;</code>
       */
      public Builder setDisplayNameEn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        displayNameEn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string displayNameEn = 7;</code>
       */
      public Builder clearDisplayNameEn() {
        bitField0_ = (bitField0_ & ~0x00000040);
        displayNameEn_ = getDefaultInstance().getDisplayNameEn();
        onChanged();
        return this;
      }
      /**
       * <code>required string displayNameEn = 7;</code>
       */
      public Builder setDisplayNameEnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        displayNameEn_ = value;
        onChanged();
        return this;
      }

      // required string valueType = 8;
      private Object valueType_ = "";
      /**
       * <code>required string valueType = 8;</code>
       */
      public boolean hasValueType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string valueType = 8;</code>
       */
      public String getValueType() {
        Object ref = valueType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          valueType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string valueType = 8;</code>
       */
      public com.google.protobuf.ByteString
          getValueTypeBytes() {
        Object ref = valueType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          valueType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string valueType = 8;</code>
       */
      public Builder setValueType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        valueType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string valueType = 8;</code>
       */
      public Builder clearValueType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        valueType_ = getDefaultInstance().getValueType();
        onChanged();
        return this;
      }
      /**
       * <code>required string valueType = 8;</code>
       */
      public Builder setValueTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        valueType_ = value;
        onChanged();
        return this;
      }

      // required string uint = 9;
      private Object uint_ = "";
      /**
       * <code>required string uint = 9;</code>
       */
      public boolean hasUint() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string uint = 9;</code>
       */
      public String getUint() {
        Object ref = uint_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uint_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string uint = 9;</code>
       */
      public com.google.protobuf.ByteString
          getUintBytes() {
        Object ref = uint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uint = 9;</code>
       */
      public Builder setUint(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        uint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uint = 9;</code>
       */
      public Builder clearUint() {
        bitField0_ = (bitField0_ & ~0x00000100);
        uint_ = getDefaultInstance().getUint();
        onChanged();
        return this;
      }
      /**
       * <code>required string uint = 9;</code>
       */
      public Builder setUintBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        uint_ = value;
        onChanged();
        return this;
      }

      // required string cateType = 10;
      private Object cateType_ = "";
      /**
       * <code>required string cateType = 10;</code>
       */
      public boolean hasCateType() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required string cateType = 10;</code>
       */
      public String getCateType() {
        Object ref = cateType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cateType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string cateType = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCateTypeBytes() {
        Object ref = cateType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cateType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cateType = 10;</code>
       */
      public Builder setCateType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        cateType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cateType = 10;</code>
       */
      public Builder clearCateType() {
        bitField0_ = (bitField0_ & ~0x00000200);
        cateType_ = getDefaultInstance().getCateType();
        onChanged();
        return this;
      }
      /**
       * <code>required string cateType = 10;</code>
       */
      public Builder setCateTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        cateType_ = value;
        onChanged();
        return this;
      }

      // required string signalCode = 11;
      private Object signalCode_ = "";
      /**
       * <code>required string signalCode = 11;</code>
       */
      public boolean hasSignalCode() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required string signalCode = 11;</code>
       */
      public String getSignalCode() {
        Object ref = signalCode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          signalCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string signalCode = 11;</code>
       */
      public com.google.protobuf.ByteString
          getSignalCodeBytes() {
        Object ref = signalCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          signalCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string signalCode = 11;</code>
       */
      public Builder setSignalCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        signalCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string signalCode = 11;</code>
       */
      public Builder clearSignalCode() {
        bitField0_ = (bitField0_ & ~0x00000400);
        signalCode_ = getDefaultInstance().getSignalCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string signalCode = 11;</code>
       */
      public Builder setSignalCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        signalCode_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem)
    }

    static {
      defaultInstance = new VehicleStatusItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem)
  }

  // repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;
  public static final int ITEMS_FIELD_NUMBER = 1;
  private java.util.List<com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem> items_;
  /**
   * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
   */
  public java.util.List<com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
   */
  public java.util.List<? extends com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItemOrBuilder>
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
   */
  public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
   */
  public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  private void initFields() {
    items_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    for (int i = 0; i < getItemsCount(); i++) {
      if (!getItems(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItemsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusInfo.internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusInfo.internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.class, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.Builder.class);
    }

    // Construct using com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusInfo.internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_descriptor;
    }

    public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems getDefaultInstanceForType() {
      return com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.getDefaultInstance();
    }

    public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems build() {
      com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems buildPartial() {
      com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems result = new com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems(this);
      int from_bitField0_ = bitField0_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems) {
        return mergeFrom((com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems other) {
      if (other == com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {

          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;
    private java.util.List<com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        items_ = new java.util.ArrayList<com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public java.util.List<com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public Builder setItems(
        int index, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public Builder setItems(
        int index, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public Builder addItems(com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public Builder addItems(
        int index, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public Builder addItems(
        com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public Builder addItems(
        int index, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public Builder addAllItems(
        Iterable<? extends com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        super.addAll(values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public java.util.List<? extends com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItemOrBuilder>
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.getDefaultInstance());
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.getDefaultInstance());
    }
    /**
     * <code>repeated .com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
     */
    public java.util.List<com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder>
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItemOrBuilder>
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem.Builder, com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems)
  }

  static {
    defaultInstance = new VehicleStatusItems(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems)
}

