// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VehicleStatusInfo.proto

package com.iammybest.hbase.springboot.hbase.protobuf;

public final class VehicleStatusInfo {
  private VehicleStatusInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_VehicleStatusItem_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_VehicleStatusItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027VehicleStatusInfo.proto\022*com.timanetwo" +
      "rks.tpc.entity.hbase.protobuf\"\335\002\n\022Vehicl" +
      "eStatusItems\022_\n\005items\030\001 \003(\0132P.com.timane" +
      "tworks.tpc.entity.hbase.protobuf.Vehicle" +
      "StatusItems.VehicleStatusItem\032\345\001\n\021Vehicl" +
      "eStatusItem\022\014\n\004gvid\030\001 \002(\t\022\026\n\016oringinalVa" +
      "lue\030\002 \002(\t\022\r\n\005value\030\003 \002(\t\022\022\n\nsignNameZh\030\004" +
      " \002(\t\022\022\n\nsignNameEn\030\005 \002(\t\022\025\n\rdisplayNameZ" +
      "h\030\006 \002(\t\022\025\n\rdisplayNameEn\030\007 \002(\t\022\021\n\tvalueT" +
      "ype\030\010 \002(\t\022\014\n\004uint\030\t \002(\t\022\020\n\010cateType\030\n \002(",
      "\t\022\022\n\nsignalCode\030\013 \002(\tBA\n*com.timanetwork" +
      "s.tpc.entity.hbase.protobufB\021VehicleStat" +
      "usInfoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_descriptor,
              new String[] { "Items", });
          internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_VehicleStatusItem_descriptor =
            internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_descriptor.getNestedTypes().get(0);
          internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_VehicleStatusItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleStatusItems_VehicleStatusItem_descriptor,
              new String[] { "Gvid", "OringinalValue", "Value", "SignNameZh", "SignNameEn", "DisplayNameZh", "DisplayNameEn", "ValueType", "Uint", "CateType", "SignalCode", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
