// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VehicleStatusInfo.proto

package com.iammybest.hbase.springboot.hbase.protobuf;

public interface VehicleStatusItemsOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;
  /**
   * <code>repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
   */
  java.util.List<com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem>
      getItemsList();
  /**
   * <code>repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
   */
  com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItem getItems(int index);
  /**
   * <code>repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
   */
  java.util.List<? extends com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItemOrBuilder>
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleStatusItems.VehicleStatusItem items = 1;</code>
   */
  com.iammybest.hbase.springboot.hbase.protobuf.VehicleStatusItems.VehicleStatusItemOrBuilder getItemsOrBuilder(
          int index);
}
