//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: VehicleStatus.proto
//
//package com.iammybest.hbase.springboot.hbase.protobuf;
//
//public interface VehicleDiagnosisCodesOrBuilder
//    extends com.google.protobuf.MessageOrBuilder {
//
//  // repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleDiagnosisCodes.VehicleDiagnosisCode codes = 1;
//  /**
//   * <code>repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleDiagnosisCodes.VehicleDiagnosisCode codes = 1;</code>
//   */
//  java.util.List<com.iammybest.hbase.springboot.hbase.protobuf.VehicleDiagnosisCodes.VehicleDiagnosisCode>
//      getCodesList();
//  /**
//   * <code>repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleDiagnosisCodes.VehicleDiagnosisCode codes = 1;</code>
//   */
//  com.iammybest.hbase.springboot.hbase.protobuf.VehicleDiagnosisCodes.VehicleDiagnosisCode getCodes(int index);
//  /**
//   * <code>repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleDiagnosisCodes.VehicleDiagnosisCode codes = 1;</code>
//   */
//  int getCodesCount();
//  /**
//   * <code>repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleDiagnosisCodes.VehicleDiagnosisCode codes = 1;</code>
//   */
//  java.util.List<? extends com.iammybest.hbase.springboot.hbase.protobuf.VehicleDiagnosisCodes.VehicleDiagnosisCodeOrBuilder>
//      getCodesOrBuilderList();
//  /**
//   * <code>repeated .com.timanetworks.tpc.entity.hbase.protobuf.VehicleDiagnosisCodes.VehicleDiagnosisCode codes = 1;</code>
//   */
//  com.iammybest.hbase.springboot.hbase.protobuf.VehicleDiagnosisCodes.VehicleDiagnosisCodeOrBuilder getCodesOrBuilder(
//          int index);
//}
