//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: VehicleStatus.proto
//
//package com.iammybest.hbase.springboot.hbase.protobuf;
//
//public final class VehicleDiagnosis {
//  private VehicleDiagnosis() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//  }
//  static com.google.protobuf.Descriptors.Descriptor
//    internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleDiagnosisCodes_descriptor;
//  static
//    com.google.protobuf.GeneratedMessage.FieldAccessorTable
//      internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleDiagnosisCodes_fieldAccessorTable;
//  static com.google.protobuf.Descriptors.Descriptor
//    internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleDiagnosisCodes_VehicleDiagnosisCode_descriptor;
//  static
//    com.google.protobuf.GeneratedMessage.FieldAccessorTable
//      internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleDiagnosisCodes_VehicleDiagnosisCode_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    String[] descriptorData = {
//      "\n\023VehicleStatus.proto\022*com.timanetworks." +
//      "tpc.entity.hbase.protobuf\"\361\002\n\025VehicleDia" +
//      "gnosisCodes\022e\n\005codes\030\001 \003(\0132V.com.timanet" +
//      "works.tpc.entity.hbase.protobuf.VehicleD" +
//      "iagnosisCodes.VehicleDiagnosisCode\032\360\001\n\024V" +
//      "ehicleDiagnosisCode\022\014\n\004type\030\001 \001(\t\022\014\n\004cod" +
//      "e\030\002 \001(\t\022\021\n\tshow_code\030\003 \001(\t\022\024\n\014failure_ty" +
//      "pe\030\004 \001(\t\022\031\n\021abnormal_ecu_code\030\005 \001(\t\022\r\n\005v" +
//      "alue\030\006 \002(\t\022\016\n\006ecu_id\030\007 \002(\t\022\020\n\010ecu_name\030\010" +
//      " \002(\t\022\017\n\007lamp_on\030\t \002(\t\022\022\n\nis_current\030\n \002(",
//      "\t\022\r\n\005level\030\013 \002(\t\022\023\n\013description\030\014 \002(\tB@\n" +
//      "*com.timanetworks.tpc.entity.hbase.proto" +
//      "bufB\020VehicleDiagnosisP\001"
//    };
//    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
//      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
//        public com.google.protobuf.ExtensionRegistry assignDescriptors(
//            com.google.protobuf.Descriptors.FileDescriptor root) {
//          descriptor = root;
//          internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleDiagnosisCodes_descriptor =
//            getDescriptor().getMessageTypes().get(0);
//          internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleDiagnosisCodes_fieldAccessorTable = new
//            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
//              internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleDiagnosisCodes_descriptor,
//              new String[] { "Codes", });
//          internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleDiagnosisCodes_VehicleDiagnosisCode_descriptor =
//            internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleDiagnosisCodes_descriptor.getNestedTypes().get(0);
//          internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleDiagnosisCodes_VehicleDiagnosisCode_fieldAccessorTable = new
//            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
//              internal_static_com_timanetworks_tpc_entity_hbase_protobuf_VehicleDiagnosisCodes_VehicleDiagnosisCode_descriptor,
//              new String[] { "Type", "Code", "ShowCode", "FailureType", "AbnormalEcuCode", "Value", "EcuId", "EcuName", "LampOn", "IsCurrent", "Level", "Description", });
//          return null;
//        }
//      };
//    com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        }, assigner);
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
